hostname := env_var('NIX_HOSTNAME')
project_dir := "~/projects/ekawatani/nix-configs"
nix_dir := project_dir + "#" + hostname

import './.config/just/nix.just'
import './.config/just/nixos.just'
import './.config/just/home-manager.just'

default:
  just --list
